version: '2.0'

services:
  postgresdb:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - my-network
    ports:
      - "5432:5432"

  app:
    image: bora-game-java-app
    networks:
      - my-network
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
networks:
  my-network:
    driver: bridge