version: '2.0'

services:
  app:
    image: bora-game-java-app
    networks:
      - my-network
    depends_on:
      - postgresdb
    restart: on-failure
    build: .
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  postgresdb:
    image: ubuntu/postgres:14-22.04_beta
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - my-network
    ports:
      - "5432:5432"
networks:
  my-network:
    driver: bridge