services:
  mygamepostgres:
    image: postgres:14.15
    container_name: mypostgrescontainer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: Game
    volumes:
      - ./.db:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    networks:
      - mygamenetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  mygameapp:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "java",
        "-Dawt.useSystemAAFontSettings=on",
        "-Dswing.aatext=true",
        "-Dawt.useSystemAAFontSettings=on",
        "-Dsun.java2d.uiScale=1",
        "-jar",
        "mygame.jar",
        "--dburl=${DB_URL}",
        "--dbuser=postgres",
        "--dbpassword=${POSTGRES_PASSWORD}"
      ]
    environment:
      DISPLAY: "${DISPLAY}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user/$(id -u)/wayland-0:/run/user/1000/wayland-0:rw
    depends_on:
      mygamepostgres:
        condition: service_healthy
    networks:
      - mygamenetwork
networks:
  mygamenetwork:
    driver: bridge
