version: '3'

services:
  postgresdb:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - my-network
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - "5432:5432"  # Port forwarding for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U UNIFI2024 -d bora"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  my-network:
    driver: bridge

secrets:
  postgres_password:
    file: ./postgres_password.txt
  postgres_user:
    file: ./postgres_user.txt
  postgres_db:
    file: ./postgres_db.txt
