# This workflow will build a Java project with Maven and Docker

name: Java CI with Maven and Docker in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build in Linux
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache local Maven repository
            uses: actions/cache@v4
            with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                ${{ runner.os }}-maven
      - name: Build with Maven
        run: mvn verify
        working-directory: com.boracompany.mygame
