name: SonarCloud with Pre-Generated Report

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full repository clone for accurate analysis

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distributions are also supported

      # Step 3: Cache SonarCloud packages
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Step 4: Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Step 5: Generate JaCoCo coverage report
      - name: Generate JaCoCo Report
        working-directory: com.boracompany.mygame
        run: |
          xvfb-run mvn clean verify -Pjacoco \
            -Djacoco.outputDir=target/site/jacoco

      # Step 6: Verify JaCoCo report
      - name: List JaCoCo Report Directory
        working-directory: com.boracompany.mygame
        run: |
          ls -la target/site/jacoco/

      # Step 7: Run SonarCloud analysis
      - name: SonarCloud Analysis
        working-directory: com.boracompany.mygame
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          xvfb-run mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.cpd.exclusions=**/generated/**/*.java,**/CreateMapView.java,**/CreatePlayerView.java,**/MainMenuView.java,**/PlayerAttackView.java \
            -Dsonar.issue.ignore.multicriteria=e2e_rule,ignore_cycles \
            -Dsonar.issue.ignore.multicriteria.e2e_rule.ruleKey=java:S3577 \
            -Dsonar.issue.ignore.multicriteria.e2e_rule.resourceKey=**/MyGameAppE2E.java \
            -Dsonar.issue.ignore.multicriteria.ignore_cycles.ruleKey=javaarchitecture:S7027 \
            -Dsonar.issue.ignore.multicriteria.ignore_cycles.resourceKey=**/*.java \
            -Dsonar.projectKey=BoraArseven_MyGame \
            -Dsonar.host.url=https://sonarcloud.io

